[project]
name = "akin"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "justinbt1", email = "85031828+justinbt1@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = [
    "cython>=3.2.9",
    "mmh3>=5.2.1",
    "numpy>=2.5.1",
    "tqdm>=4.70.0",
]

[project.scripts]
akin = "akin:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
